# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5540ab8fabed9622c842b65eff9630511e907356b15feef744842de3782925e7130787698fb37b8a53faef34f29d77feb53fc807ced4ad7fce9ec4e4b5a51622

test:
  secret_key_base: 39ba46d2b8b33d0e50e850e7ca2de9368831fd1e3422b8b90ce1d39ae94117952224c19caafe4cfea6b75bbd2474d38a55e56a7334bd5ca8e25b852ad7c4ef01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
